Income: "rgba(0,0,255,0.5)"
Bank: "grey"
House Total: "rgba(255,0,0,0.5)"
Fixed Expense: "rgba(255,0,0,0.5)"
Variable Expense: "rgba(125,0,0,0.5)"
Savings: "rgba(0,150,0,0.5)"
Revolut: "magenta"
Fixed Pocket: "orange"
Net: "rgba(0,255,0,0.5)"
Lukas Taoglas: "rgba(0,255,0,0.5)"
Leana GH: "rgba(0,255,0,0.5)"
Lukas BOI: "rgba(0,0,255,0.5)"
Leana AIB: "rgba(255,0,0,0.5)"